name: dartnissanconnect
description: A library for the NissanConnect API.
version: 1.0.0
homepage: https://gitlab.com/tobiaswkjeldsen/dartnissanconnect
author: Tobias Westergaard Kjeldsen <tobias@wkjeldsen.dk>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: '^0.17.0'
  http: '^0.13.1'

dev_dependencies:
  test: '^1.3.0'
